/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tainting;

import calledmethods.TestC;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        TaintExample classUnderTest = new TaintExample();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testCrash() {
        System.out.println(TestC.builder().build());
    }
}
