/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tainting;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        TaintExample classUnderTest = new TaintExample();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
